### ISSUE TITLE
Mixing ratio and relative humidity calculation

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/eurec4a_snd#3]
Check whether the used formulas are correct/precise enough.

Since the sonde measures relative humidity directly, it should be checked, which formula is used in order to derive the dewpoint to be consistent.

**Comment by deszoeke** [comment]
I have the moist thermodynamics functions from Bolton (1980) coded up into python. I can't seem to upload them with this dialogue.

Also metpy has thermodynamic functions, that are probably used commonly by pythonistas. I haven't checked their accuracy.

**Comment by observingClouds** [comment]
This is great! Are you able to make a pull request?

However, my idea was that I would like to use the same function Vaisala used to calculate the dewpoint temperature from the relative humidity to retrieve back the actually measured RH.

**Comment by deszoeke** [comment]
I've still yet to figure out how to make a useful pull request. Do you want me to implement the functions somewhere in your processing?

Vaisala directly measures RH, so we can use whatever functions we like (e.g. that suit our accuracy requirements) to compute Td, specific humidity, and mixing ratio. The MW41 can optionally output these in the EDT files, but the function they use to generate them is hidden to me. Perhaps it's available in the MW41 manual. I googled around for a MW41 or DigiCORA manual, but couldn't find one. Under the circumstances, I am happy to use my function because it is accurate and reproducible. I know it and can use it consistently.

**Comment by observingClouds** [comment]
I've implemented your functions in the latest version (v.0.0.45). However, I still wait for Vaisala to come back to me to provide me the exact functions as I also couldn't find them online.

**Comment by observingClouds** [comment]
The formula used by the MW41 to convert RH to dewpoint temperature is

![image](https://user-images.githubusercontent.com/43613877/71702229-108f1680-2d83-11ea-9eb8-7b6f9b375e87.png)
where
![image](https://user-images.githubusercontent.com/43613877/71702274-459b6900-2d83-11ea-9f76-7a317a874e35.png)

To calculate the originally measured RH from the dew point temperature given in the BUFR file, the formula
![image](https://user-images.githubusercontent.com/43613877/71702427-4da7d880-2d84-11ea-8c34-099848f11d2d.png)
follows.

**Comment by deszoeke** [comment]
Aha. Now I understand the BUFR files give the derived dew point, so you want to invert back to original RH with the exact function used. Nice job.

Simon
from my mobile

On Dec 10, 2019, at 9:19 PM, Hauke Schulz <notifications@github.com> wrote:

﻿

This is great! Are you able to make a pull request?

However, my idea was that I would like to use the same function Vaisala used to calculate the dewpoint temperature from the relative humidity to retrieve back the actually measured RH.

**Comment by deszoeke** [comment]
Ok, I’ve downloaded the latest version of eurec4a_snd for use on the Ron Brown.

-Simon

On Jan 2, 2020, at 10:57 PM, Hauke Schulz <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3<https://github.com/observingClouds/eurec4a_snd/issues/3> via 9312b55<https://github.com/observingClouds/eurec4a_snd/commit/9312b55d4d3196c931207e5a44ebea76733fc838>.

**Comment by observingClouds** [comment]
Great! Let me know, in case you are facing any difficulties and I'm happy to have a look at your first Ron Brown sounding!
