### ISSUE TITLE
unhelpful warnings

### ISSUE THREAD

**Issue by deszoeke** [observingClouds/eurec4a_snd#6]
**Describe the bug**
I get two unhelpful warnings when running 'sounding_converter', even though it does convert my BUFR file. One warning is about not being a git repository, the second is that 'No version of the converter could be found.'

**To Reproduce**
Run
```
test_eurec4a_sounding_converter sdeszoek$ sounding_converter -i ./BUFR/bufr309052_all_20190328_1813_0.bfr -c ./meta_information.ini`
```

Result:
These two error/warning messages:
```
fatal: not a git repository (or any of the parent directories): .git
WARNING - root - main - No version of the converter could be found! Please consider the installation via conda or if this is not working clone the git repository
```

**Expected behavior**
I think the INFO lines, though verbose, are the expected correct behavior.
```
INFO - root - main - Version of script: 0.0.43 (conda package), -- (git version)
INFO - root - main - Files to process ['bufr309052_all_20190328_1813_0.bfr']
INFO - root - main - Reading file number 0
INFO - root - main - DONE: BUFR/bufr309052_all_20190328_1813_0.bfr converted to NC/RHB_SoundingDescentProfile_15N54W_20190328_1813.nc
```

**Error message**
Paste error message if available (make sure to remove personal details)

**Environment (please complete the following information):**
 - OS: MacOS 'Darwin ... 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64'
 - python-version 3.7.3
 - eurec4a-version 0.0.43 (conda list | grep eurec4a)

**Comment by observingClouds** [comment]
Thanks @deszoeke for reporting this! The aggressive warning message is handled differently now.
